import {StyleSheet, Dimensions} from 'react-native';
const {height, width} = Dimensions.get('screen');
export default StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  screenContainersafe: {
    flex: 1,
    backgroundColor: '#2B4F8C',
  },
  headerContainer: {
    flexDirection: 'row',
    paddingTop: 20,
    paddingBottom: 4,
    backgroundColor: '#2B4F8C',
  },
  headerText: {
    color: 'white',
    textAlignVertical: 'center',
    marginLeft: width * 0.15,
    fontSize: 20,
  },
  itemcard: {
    backgroundColor: '#fff',
    width: width,
    height: height * 0.3,
    marginTop: width / 100,
  },
  inputContainer: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    flex: 1,
    marginLeft: 10,
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 2,
  },
  listItem: {
    backgroundColor: '#fff',
    flex: 1,
    alignSelf: 'center',
    flexDirection: 'row',
    borderRadius: 5,
  },
  bodyContainer: {
    flex: 1,
    backgroundColor: 'silver',
  },
  btnSubmit: {
    width: width * 0.9,
    marginLeft: width * 0.05,
    height: height / 15,
    borderRadius: 10,
    justifyContent: 'center',
    marginVertical: 10,
    backgroundColor: '#2B4F8C',
  },
  address: {
    marginTop: 5,
    fontSize: height / 50,
  },
  addresstitle: {
    fontWeight: 'bold',
    fontSize: 17,
    color: '#000',
  },
  paymentoption: {
    backgroundColor: '#fff',
    marginTop: height / 100,
  },
  option: {
    flexDirection: 'row',
    marginTop: height / 50,
  },
  count: {
    backgroundColor: '#fff',
    marginTop: height / 100,
  },
  centeredView: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    alignSelf: 'center',
  },
  modalView: {
    margin: 20,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    justifyContent: 'center',
    height: height / 3,
    width: width / 1.2,
  },
  openButton: {
    backgroundColor: '#F194FF',
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 20,
  },
  addressView: {flex: 1, margin: 10},
  addressViewRow: {flexDirection: 'row', justifyContent: 'space-between'},
  greenText: {color: 'green', marginRight: 5, fontSize: 17},
  infoView: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: 10,
  },
  payText: {fontSize: 16, marginLeft: 10, color: '#000'},
  method: {marginLeft: width / 40, fontSize: 16, color: '#000'},
  txtMoney: {fontSize: 17, marginHorizontal: 10, color: '#000'},
  blankView: {
    backgroundColor: '#fff',
    marginBottom: 5,
    height: height / 7.5,
  },
  TotalView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  btnXacNhan: {color: 'white', fontSize: 20, alignSelf: 'center'},
  modalMain: {
    width: width / 1.5,
    height: height / 15,
    borderRadius: 13,
    backgroundColor: '#2B4F8C',
    justifyContent: 'center',
  },
  btnContinue: {
    marginTop: 5,
    fontSize: 17,
    color: '#fff',
    textAlign: 'center',
  },
  btnConfirm: {marginTop: 5, fontSize: 17, color: 'green'},
  Amount: {marginTop: 5, fontSize: 17, marginBottom: 20},
  rowView: {flexDirection: 'row'},
  btnThanhToan: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    backgroundColor: '#2196F3',
    width: width / 2.5,
  },
  btnClose: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    backgroundColor: '#2196F3',
    width: width / 2.5,
    marginLeft: 5,
  },
});
