import { StyleSheet, Platform } from 'react-native';
import SIZE from 'constants/size';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#1ba8ff',
    },
    header: {
        flex: 1,
        justifyContent: 'flex-end',
        paddingHorizontal: 20,
        paddingBottom: 50,
    },
    footer: {
        flex: 3,
        backgroundColor: '#fff',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        paddingHorizontal: 20,
        paddingVertical: 30,
        margin: SIZE.DEVICE_HEIGHT / 100,
    },
    text_header: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 30,
    },
    text_footer: {
        color: '#1ba8ff',
        fontSize: 18,
    },
    action: {
        flexDirection: 'row',
        marginTop: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#000',
        paddingBottom: 5,
    },
    actionError: {
        flexDirection: 'row',
        marginTop: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#FF0000',
        paddingBottom: 5,
    },
    textInput: {
        flex: 1,
        marginTop: Platform.OS === 'ios' ? 0 : -12,
        paddingLeft: 10,
        color: '#1ba8ff',
    },
    errorMsg: {
        color: '#FF0000',
        fontSize: 14,
    },
    button: {
        alignItems: 'center',
        marginTop: SIZE.DEVICE_WIDTH / 15,
    },
    signIn: {
        width: '100%',
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
        backgroundColor: 'red',
    },
    signIn1: {
        width: '49%',
        height: 53,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
    },
    textSign: {
        fontSize: 18,
        fontWeight: 'bold',
        color: 'white',
    },
    modalView: {
        margin: 20,
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 35,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        justifyContent: 'center',
    },
    modalText: {
        marginBottom: 15,
        textAlign: 'center',
        fontSize: 20,
        color: '#a2459a',
    },
    modalText1: {
        marginBottom: 15,
        textAlign: 'center',
        fontSize: 20,
        color: 'red',
    },
    centeredView: {
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
    },
    modalView1: {
        margin: 10,
        backgroundColor: '#fff',
        borderRadius: 20,
        paddingHorizontal: 15,
        paddingTop: 10,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        width: SIZE.DEVICE_WIDTH / 1.1,
        height: SIZE.DEVICE_HEIGHT / 4.5,
    },
    textPass: {
        borderColor: '#000',
        borderRadius: 15,
        width: SIZE.DEVICE_WIDTH / 1.2,
        height: SIZE.DEVICE_HEIGHT / 10,
        marginVertical: 10,
        borderWidth: 2,
        padding: 10,
    },
    textSubmitPasss: {
        fontWeight: 'bold',
        fontSize: 20,
        color: '#fff',
        textAlign: 'center',
    },
    btnSubmit: {
        backgroundColor: '#0077b5',
        borderRadius: 10,
        width: SIZE.DEVICE_WIDTH / 3,
        height: SIZE.DEVICE_HEIGHT / 20,
        alignSelf: 'center',
        justifyContent: 'center',
    },
    btnEmail: {
        width: SIZE.DEVICE_WIDTH / 15,
        borderRadius: 10,
    },
});
