import {StyleSheet} from 'react-native';
import SIZE from 'constants/size';

export default StyleSheet.create({
  screenContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  btncomment: {
    height: SIZE.DEVICE_HEIGHT / 15,
    width: SIZE.DEVICE_WIDTH / 1.5,
    borderRadius: 25,
    backgroundColor: '#2B4F8C',
    justifyContent: 'center',
    marginTop: 5,
    alignSelf: 'center',
  },
  itemImage: {
    width: SIZE.DEVICE_WIDTH / 5,
    height: SIZE.DEVICE_HEIGHT / 8,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginLeft: 5,
  },
  itemName: {
    fontSize: 14,
    color: 'black',
    marginHorizontal: 10,
    marginRight: SIZE.DEVICE_WIDTH / 5,
  },
  itemPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
    marginHorizontal: 10,
  },
  itemContainer1: {
    width: SIZE.DEVICE_WIDTH - 20,
    height: SIZE.DEVICE_HEIGHT / 6,
    borderColor: 'silver',
    borderWidth: 1,
    marginHorizontal: 10,
    marginVertical: 2,
    borderRadius: 15,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    margin: 20,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    height: SIZE.DEVICE_HEIGHT / 1.7,
    width: SIZE.DEVICE_WIDTH / 1.1,
  },
  modalText: {
    textAlign: 'center',
    fontSize: 20,
    color: '#2B4F8C',
    fontWeight: 'bold',
  },
  btnBuyNow: {
    height: SIZE.DEVICE_HEIGHT / 14,
    width: SIZE.DEVICE_WIDTH / 1.5,
    backgroundColor: '#2B4F8C',
    borderRadius: 25,
    justifyContent: 'center',
    marginTop: 10,
  },
  modalView1: {
    margin: 20,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    height: SIZE.DEVICE_HEIGHT / 4,
    alignItems: 'center',
  },
  txtCodeName: {
    color: '#000',
    marginHorizontal: 10,
    textAlign: 'center',
    fontSize: 15,
    fontWeight: 'bold',
  },
  txtPrice: {
    color: '#000',
    marginHorizontal: 10,
  },
  loadContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  txttitle: {
    color: '#000',
    marginHorizontal: 20,
    textAlign: 'center',
    fontSize: 15,
  },
  txtSent: {
    color: '#fff',
    fontSize: 20,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  txtInput: {
    borderColor: '#2B4F8C',
    borderWidth: 1,
    height: SIZE.DEVICE_HEIGHT * 0.3,
    fontSize: 18,
    borderRadius: 10,
  },
  row: {
    flexDirection: 'row',
  },
  modal: {
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  btnRating: {
    width: SIZE.DEVICE_WIDTH / 15,
    marginRight: SIZE.DEVICE_WIDTH / 30,
  },
});
