const SCENE_NAMES = {
  // Scene name
  REPORT: 'REPORT_SCREEN',
  STATISTIC: 'STATISTIC_SCREEN',
  COMMENT: 'COMMENT_SCREEN',
  REGISTER_STORE: 'REGISTER_STORE_SCREEN',
  STORE_PROFILE: 'STORE_PROFILE_SCREEN',
  DETAIL_STORE_PRODUCT: 'DETAIL_STORE_PRODUCT_SCREEN',
  STORE_PRODUCT: 'STORE_PRODUCT_SCREEN',
  SELLERPRODUCT: 'SELLERPRODUCT_SCREEN',
  SEARCH: 'SEARCH_SCREEN',
  REGISER_OTP: 'REGISER_OTP_SCREEN',
  ZALOPAY: 'ZALOPAY_SCREEN',
  PAYMENT_METHOD: 'PAYMENT_METHOD_SCREEN',
  DETAIL_ADDRESS: 'DETAIL_ADDRESS_SCREEN',
  PRODUCT: 'PRODUCT_SCREEN',
  HOME: 'HomeScreen',
  CATEGORY: 'CateScreen',
  NOTIFY: 'NotifyScreen',
  MAIN: 'MainScreen',
  TopStackLogin: 'TopStackLogin',
  TopStackOrder: 'TopStackOrder',
  SIGN_IN: 'SignInScreen',
  PROFILE: 'PROFILE_SCREEN',
  GET_START: 'GetStartContainer',
  DUMMY: 'DUMMY_SCREEN',
  LOGIN: 'Login_Screen',
  Register: 'Register_Screen',
  PROFILEMAIN: 'PROFILEMAIN_SCREEN',
  Route_Contents: 'Route_Contents',
  CART_SCREEN: 'CART_SCREEN',
  InfoUser: 'InfoUser',
  AddRessScreen: 'AddRessScreen',
  OrderXuli: 'OrderXuli',
  Order_LayHangScreen: 'Order_LayHangScreen',
  Order_DangVanChuyen: 'Order_DangVanChuyen',
  Order_DaGiao: 'Order_DaGiao',
  Order_DaHuy: 'Order_DaHuy',
  Order_TraHang: 'Order_TraHang',
  RatingScreen: 'RatingScreen',
  TopRatingScreen: 'TopRatingScreen',
  DetailOrderContainer: 'DetailOrderContainer',
  MyStoreOptionContainer: 'MyStoreOptionContainer',
  AddProductContainer: 'AddProductContainer',
  ChatContainer: 'ChatContainer',
  ChatBoxContainer: 'ChatBoxContainer',
  Route_ContentViews: 'Route_ContentViews',
  ProductNewContainer: 'ProductNewContainer',
};

export default SCENE_NAMES;
