import { StyleSheet, Dimensions } from 'react-native';
import { normalize } from 'react-native-elements';
const { height, width } = Dimensions.get('screen');
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#2B4F8C',
  },
  subcontainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  resView: {
    marginHorizontal: 20,
  },
  stepImg: {
    height: height / 15,
    width: width / 2,
    resizeMode: 'stretch',
    alignSelf: 'center',
  },
  logoimg: {
    height: height / 3,
    width: width / 1.5,
    resizeMode: 'stretch',
    alignSelf: 'center',
  },
  infoView: {
    width: width,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  ChangeStatus: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  nameText: {
    fontSize: height / 50,
    marginTop: height / 50,
  },
  nameInput: {
    borderWidth: 1,
    borderRadius: 10,
    width: width * 0.9,
    height: height / 15,
    borderColor: '#6Ec0B6',
    paddingHorizontal: 8,
    marginTop: 10,
  },
  btnthem: {
    backgroundColor: '#6Ec0B6',
    height: height / 20,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    paddingHorizontal: 10,
  },
  themAdd: {
    color: '#fff',
    fontSize: 18,
  },
  pre: {
    height: height / 20,
    width: width / 2.5,
    backgroundColor: '#666666',
    borderRadius: height / 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  next: {
    height: height / 20,
    backgroundColor: '#2B4F8C',
    marginBottom: height / 50,
    borderRadius: height / 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 40,
    marginTop: 15,
  },
  userContainer: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    borderTopColor: '#ededed',
  },
  totalContainer1: {
    marginTop: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  nameView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  whiteText: {
    color: '#000',
    fontSize: 17,
  },
  totalContainer: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    backgroundColor: '#EEEEEE',
  },
  textContainer: {
    marginLeft: 10,
  },
  welcomeText: {
    color: 'black',
    fontSize: 15,
    width: '100%',
    borderWidth: 2,
    borderColor: '#6Ec0B6',
    borderRadius: 10,
    marginTop: 10,
    paddingHorizontal: 8,
  },
  divider: {
    height: 2,
  },
  errorMsg: {
    color: '#FF0000',
    fontSize: 15,
  },
  errtext: {
    color: 'red',
    fontSize: 15,
  },
  modalView: {
    margin: 20,
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    justifyContent: 'center',
  },
  ModalContainer: {
    maxHeight: height / 2.3,
    width: width - 20,
    borderRadius: 15,
    paddingHorizontal: 20,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignSelf: 'center',
    flex: 1,
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 20,
    color: '#2B4F8C',
  },
  modalText1: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 20,
    color: '#6Ec0B6',
  },
  centeredView: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  picker: {
    height: 40,
    width: width,
    color: 'gray',
  },
  pickerView: {
    height: height / 20,
    justifyContent: 'center',
    borderColor: '#6Ec0B6',
    borderWidth: 2,
    borderRadius: height / 50,
  },
  picker1: {
    height: height / 25,
    width: width / 2.3,
    color: 'gray',
  },
  marTen: { marginLeft: 10 },
  marHori: { marginHorizontal: 10 },
  greenText: { color: '#6Ec0B6', fontSize: 20 },
  btnSubmit: {
    backgroundColor: '#6Ec0B6',
    alignSelf: 'center',
    height: height / 20,
    width: width / 2,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: normalize(35),
  },
  subBtnText: {
    fontSize: 20,
    textAlign: 'center',
    color: 'white',
    marginTop: 5,
  },
  listItem: {
    backgroundColor: '#fff',
    alignSelf: 'center',
    flexDirection: 'row',
    borderRadius: 5,
    width: width,
  },
  address: {
    width: width * 0.8,
  },
  legacy: { width: width * 0.8, marginLeft: width * 0.1 },
});
